### ISSUE TITLE
Brain painter doe not provide the same pictures if run several times with the same template file.

### ISSUE THREAD

**Issue by nosmokingsurfer** [razvanmarinescu/brain-coloring#10]
Hello,

For some reason on the last version 59f2352f203ec23900c79ec353e1e480273dfb5a, the resulting images are different every time I launch the ```make```. I'm using blender 2.79 and Ubuntu 18

How to reproduce:

1. Run ```make``` first time. Some output will appear.
2. Rename pictures and keep them in the same folder.
3. Run ```make``` second time.
4. Visually compare images.

Here I attach some images for ```mice_template.csv``` obtained by above mentioned procedure:

![top_Image_0](https://user-images.githubusercontent.com/22825575/111920358-87efb980-8a9f-11eb-8ebc-c25c2d4d025e.png)
![top_Image_00](https://user-images.githubusercontent.com/22825575/111920360-8aeaaa00-8a9f-11eb-8e6d-e95026d6f035.png)

For ```DK_template``` it is the same - I can't paint specific segment because it maps to wrong segments every time I launch make. Looks like the inner color mapping constantly misses the elements.

**Comment by vmallela0** [comment]
Just fixed! Sorry for the trouble.
