### ISSUE TITLE
Question about the website update

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#12]
Hello,

I noticed that the Destrieux template in the github/input folder has been updated as the paper format.

May I ask if the website has been updated to support this new template?
If so, I just noticed that the template on the website was still the old one.

Thank you!

**Comment by vmallela0** [comment]
Hi, 

That's strange, we updated the website with the new template last week. The new paper formatted template should also work on the website through. I'll be sure to check it again next time we update the website. 

Take care!
