### ISSUE TITLE
Issue about the Destrieux atlas template for website

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#13]
Hello, 

I tried again the website for plotting with the new Destrieux atlas template (consistent with the paper format), but it still show errors as below:

The following regions are missing from the input .csv file: ['Thalamus-Proper', 'Lateral-Ventricle', 'Cerebellum-Cortex', 'Putamen', 'VentralDC', 'Amygdala', 'Inf-Lat-Vent', 'Hippocampus', 'Pallidum', 'Caudate', 'Accumbens-area', 'Cerebellum-White-Matter']

Make sure the correct atlas is used, and double check the example template corresponding to that atlas. Note that, currently, all regions from the template need to be assigned a number mapping to a color.

Could you please kindly help me with this problem?

Thanks!

**Comment by vmallela0** [comment]
Hi, 

These areas are all the subcortical structures. Could you please check if you included them in your csv file? You can just copy these columns from the csv template file on the website. 

Thanks

**Comment by kacey-yang** [comment]
Yes, I have those columns as shown in the new template, but in the new template, you combined right and left in one csv file.
So, it seems that the new template does not work for the website, right?

**Comment by kacey-yang** [comment]
I used the new Destrieux template csv file exactly as the one in the input folder.

**Comment by vmallela0** [comment]
Yes, that's the problem. We're in the process of making some updates and are trying to fix a few things, but we will push those changes ASAP. Sorry for the trouble!

**Comment by kacey-yang** [comment]
May I ask about when is the expected time for this fix?

**Comment by vmallela0** [comment]
I'll try my best to get it updated tomorrow. If it's urgent, I can run the data for you and get your renders back ASAP. You can email me at vmallela@csail.mit.edu .

**Comment by kacey-yang** [comment]
Tomorrow is good for me. 
Thank you very much for your kind help!

**Comment by vmallela0** [comment]
No worries. I'll ping you here when it's done.

**Comment by kacey-yang** [comment]
Sure. Thanks!

**Comment by vmallela0** [comment]
Thanks for letting us know!

It's fixed now :). Feel free to make issues/email us if you run into any more trouble.
