### ISSUE TITLE
Hide subcortical structures on right hemisphere inner view

### ISSUE THREAD

**Issue by azrin-saj** [razvanmarinescu/brain-coloring#15]
Hi there, 

I am using the BrainPainter website to generate images to display significant DK ROIs.
However, I noticed that the inner right hemisphere view shows the subcortical structures. 

Is there a way to remove the subcortical structures from being displayed by using the BrainPainter website? 

I tried deleting the columns for the subcortical structures from the DK_template.csv that was provided on the website but this does not work and will just give an error message that those regions are missing from the csv file. 

Thank you!

**Comment by vmallela0** [comment]
Currently, there's no way of doing this from the website. It is possible however, to edit the source code and remove those subcortical regions from being imported in the cortical inner functions in blendHelper.py.

**Comment by kacey-yang** [comment]
Hello!

I noticed the same problem last night, and I just wanted to ask you today and found that someone asked this question already.
If there is no way of doing this from the website, in case I will have to remove those subcortical regions later, can you briefly show us which lines of code need to change in the blendHelper.py file?

Thanks!

**Comment by vmallela0** [comment]
Yes, for sure. You need to change some things in the blendHelper.py and blendCreateSnapshot.py

1. in blendCreateSnapshot.py change the parameters for the function you're calling (I'm using cortical-inner-right-hemisphere) please change line 149 to 
```   painter = CorticalPainterInnerRight(cortFilesRight)```
I just took out the subcortical parameter there

2. In the blendHelper.py file please change the function you're using above's parameters, in this case it would be CorticalPainterInnerRight on line 238 in blendHelper.py. You need to change the parameters of the __init__ method to 
```def __init__(self, cortFiles, subcortFiles=[]): ```

That just worked for me but if you need any more help feel free to ping me here! Hope this helps :)

**Comment by kacey-yang** [comment]
Thank you!

I have tried to modify the code as the way you showed me here and it works!

**Comment by vmallela0** [comment]
Perfect! I'm glad it works.

**Comment by kacey-yang** [comment]
I just wanted to ask if in the future the website will be updated to have the subcortical structures removed from being displayed for cortical inner right view?

Thanks!

**Comment by vmallela0** [comment]
We will try to do this soon but we're also working on a few other things right now. I'll try to add this to the website in the next few weeks.

**Comment by kacey-yang** [comment]
> We will try to do this soon but we're also working on a few other things right now. I'll try to add this to the website in the next few weeks.

Thank you!
