### ISSUE TITLE
Additional question for the input range

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#16]
Sorry I still have a question regarding the range of input ROI values.

For example, if I want to plot some ROI values ranged from 0-12, rather than the default setting of 0-3, how should I modify the source code for this?

Currently, I am able to plot for the values of 0-3, but I need to do a minmax normalization to have my data fit for range of 0-3.

But now, I would like to plot my ROI values on its original scale. How could I plot the input values from 0-12 or 0-max?

Thanks!

**Comment by razvanmarinescu** [comment]
You can just normalize your input .csv data from 0-12 to 0-3, then generate the images, and then change the labels on the colorbar in report.tex (LaTeX file) from 0-3 back to 0-12.

**Comment by kacey-yang** [comment]
Thank you for your reply!

I understand your point, but I still have two concerns:

1) When I do the minmax normalization, the max value is not an integer, so I am afraid that it may not look nice, if I directly modify the max label in latex.

2) I need to plot 2 sets of brain surfaces for comparison, so I need to have the input data on the same scale. 
What I currently do is to do the minmax normalization using the min and max of the whole. 
I am kind of worried that if I will get exactly the same visualization result between figures with normalization and figures without normalization?
That is, without normalization, I plot 2 sets of figures on the scale 0-12;
with normalization, I plot 2 sets of figures on the scale 0-3.
Should they be exactly the same?

Also, is there a way to modify the source code to adjust the input range?

Thank you for your help!

**Comment by razvanmarinescu** [comment]
> When I do the minmax normalization, the max value is not an integer, so I am afraid that it may not look nice, if I directly modify the max label in latex.

To be precise, are you doing X = (X - min) / (max - min) for [0-1], then applying X = 3X for [0-3] ?  Then, after this, the max will always be 3, right (so an integer)?

> I am kind of worried that if I will get exactly the same visualization result between figures with normalization and figures without normalization?

They will be exactly the same, as you essentially "invert" the linear min-max transformation at the end in the colorbar. If you apply the same transformation on multiple images, they will be comparable. You can try this with the code, by adding up to 12 colors in the COLOR_POINTS in config.py (if it doesn't work right away, you might also need to change a counter in the code to tell it to look for up to 12 colors now). But this way, you have to write all 12 RGB values in COLOR_POINTS for all the interpolating colors in the colorbar, and you will need to find those RGB values with a color picker tool.

**Comment by kacey-yang** [comment]
> > When I do the minmax normalization, the max value is not an integer, so I am afraid that it may not look nice, if I directly modify the max label in latex.
> 
> To be precise, are you doing X = (X - min) / (max - min) for [0-1], then applying X = 3X for [0-3] ? Then, after this, the max will always be 3, right (so an integer)?
> 
> > I am kind of worried that if I will get exactly the same visualization result between figures with normalization and figures without normalization?
> 
> They will be exactly the same, as you essentially "invert" the linear min-max transformation at the end in the colorbar. If you apply the same transformation on multiple images, they will be comparable. You can try this with the code, by adding up to 12 colors in the COLOR_POINTS in config.py (if it doesn't work right away, you might also need to change a counter in the code to tell it to look for up to 12 colors now). But this way, you have to write all 12 RGB values in COLOR_POINTS for all the interpolating colors in the colorbar, and you will need to find those RGB values with a color picker tool.

Thanks for your reply!

1) What I mean is that when you say "change the labels on the colorbar in report.tex (LaTeX file) from 0-3 back to 0-12", my original max is not an integer, which means for example 12.6 is my max.

2)It seems modifying colors in the COLOR_POINTS in config.py is too complicated for me. 
I noticed a line of code in blendCreateSnapshot.py:
NR_SIGN_LEVELS = len(COLOR_POINTS)-1
Will it help with the change of input range?

Thank you!

**Comment by razvanmarinescu** [comment]
> What I mean is that when you say "change the labels on the colorbar in report.tex (LaTeX file) from 0-3 back to 0-12", my original max is not an integer, which means for example 12.6 is my max.

Ah, got it. So would you ideally like to mark only the integers somehow? If yes, you will have to make a special colorbar for your particular scenario. Sorry we can't help with this, very few users need this. Good news is that the colorbar is not difficult to make yourself anyway.  

> NR_SIGN_LEVELS = len(COLOR_POINTS)-1

No, don't change that line. I think that just adding more than 4 colors in COLOR_POINTS might be enough, but I haven't tested it. Give it a try to see if it works.

**Comment by kacey-yang** [comment]
> > What I mean is that when you say "change the labels on the colorbar in report.tex (LaTeX file) from 0-3 back to 0-12", my original max is not an integer, which means for example 12.6 is my max.
> 
> Ah, got it. So would you ideally like to mark only the integers somehow? If yes, you will have to make a special colorbar for your particular scenario. Sorry we can't help with this, very few users need this. Good news is that the colorbar is not difficult to make yourself anyway.
> 
> > NR_SIGN_LEVELS = len(COLOR_POINTS)-1
> 
> No, don't change that line. I think that just adding more than 4 colors in COLOR_POINTS might be enough, but I haven't tested it. Give it a try to see if it works.

Thanks!

May I ask about what this line of code is doing? I know here the length is 4, then minus 1, is it for the color bar?
NR_SIGN_LEVELS = len(COLOR_POINTS)-1

Also, after all these discussions with you, I think that the easiest way to plot input data ranged 0-12 is still the way you first mentioned:
"You can just normalize your input .csv data from 0-12 to 0-3, then generate the images, and then change the labels on the colorbar in report.tex (LaTeX file) from 0-3 back to 0-12."

Thank you!

**Comment by razvanmarinescu** [comment]
> May I ask about what this line of code is doing? I know here the length is 4, then minus 1, is it for the color bar?
NR_SIGN_LEVELS = len(COLOR_POINTS)-1

My bad. That line is obsolete, the variable is not used anymore. Can remove it.

> Also, after all these discussions with you, I think that the easiest way to plot input data ranged 0-12 is still the way you first mentioned:
"You can just normalize your input .csv data from 0-12 to 0-3, then generate the images, and then change the labels on the colorbar in report.tex (LaTeX file) from 0-3 back to 0-12."

I think so. This will work for any linear transformations, but indeed, the colorbar can have non-integer points. This is what you can easily do at this point. If you would like to have integer points, you will need to make your own colorbar in LaTeX or Photoshop (until we add a feature for that).

**Comment by razvanmarinescu** [comment]
Hi Kacey,

Just thought about your problem more. Actually, if you normalise e.g. [0-12.7] to [0-3], you can fix the integer issue by setting the max as the **the next higher number divisible by 3**, i.e. 15 (the next number higher than 12.7 that is divisible by 3). Then you do X = (X - min) / (max - min), where max is 15 instead of 12.7

Does this make sense? You will get a colorbar that only contains integers. The very end of the color spectrum (above 12.7) will not be used, but that is OK, right?

**Comment by kacey-yang** [comment]
> Hi Kacey,
> 
> Just thought about your problem more. Actually, if you normalise e.g. [0-12.7] to [0-3], you can fix the integer issue by setting the max as the **the next higher number divisible by 3**, i.e. 15 (the next number higher than 12.7 that is divisible by 3). Then you do X = (X - min) / (max - min), where max is 15 instead of 12.7
> 
> Does this make sense? You will get a colorbar that only contains integers. The very end of the color spectrum (above 12.7) will not be used, but that is OK, right?

Thank you for your kind reply!

I think I will go with your suggestion. 
Although it is not perfect with the very end of color spectrum unused, it is still much better than having 12.7 as the max on the color bar.

Thank you very much!
