### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#17]
Hello,

I am trying to using the website for plotting, but I am getting error message:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Thanks!

**Comment by vmallela0** [comment]
Hi Kasey, thanks for letting us know. I'll take a look ASAP and get back to you soon.

**Comment by vmallela0** [comment]
Should be fixed now. Thank you again for letting us know! Have a great day :)
