### ISSUE TITLE
Path error/windows syntax error

### ISSUE THREAD

**Issue by AngCamp** [razvanmarinescu/brain-coloring#19]
I am running Ubuntu virtual machine on windows.  When I use make after following the YouTube tutorial I get the following error
The command seems to run fine but then right at the end as it is trying to save the image a syntax error occurs.
```
Saved: 'C:\output\mice_output\top_Image_1.png'
 Time: 00:02.83 (Saving: 00:00.14)

The syntax of the command is incorrect.


Blender quit
(brainpainterEnv) wintermute@LAPTOP-6F6LEGSI:/mnt/c/Users/angus/Desktop/brain-coloring$
```

My windows is x64 bit.  I'm running the script inside a conda environment with the appropriate libraries (such as the specified version of pandas).

**Comment by vmallela0** [comment]
Hi @AngCamp, I think the error is because the output path you have entered in your config.py file is in windows format, but rather you would need to add the data to a file in your virtual machine and then copy it into your windows machine.

**Comment by AngCamp** [comment]
This is the line in my config file: OUTPUT_FOLDER = 'output/mice_output' It is in linux format.  I have not entered anything I am following the youtube tutorial.

**Comment by AngCamp** [comment]
I am wondering if its because of the folder location, the true path to the mouse_output is `C:\Users\angus\Desktop\brain-coloring\output\mice_output` but brainpainter seems to be trying to save it at `'C:\output\mice_output` which doesn't exist.

**Comment by vmallela0** [comment]
Are you running the vm on windows wsl or on a vmware machine? Could you maybe try to change the output folder string to match your desired location? (Users/angus/desktop/brain-coloring/output/mice-output)

**Comment by AngCamp** [comment]
I changed the output path in line 4 of the config.py file

`OUTPUT_FOLDER = 'Users/angus/desktop/brain-coloring/output/mice-output'`

The images are generated just fine but I still get an error:
```
Saved: 'C:\Users\angus\desktop\brain-coloring\output\mice-output\top_Image_1.png'
 Time: 00:08.39 (Saving: 00:00.50)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\angus\Desktop\brain-coloring\blendCreateSnapshot.py", line 205, in <module>
    text = genLaTex(INPUT_FILE, OUT_FOLDER, COLORS_RGB)
  File "C:\Users\angus\Desktop\brain-coloring\blendHelper.py", line 978, in genLaTex
    output_folder = os.listdir(outputFolder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Users/angus/desktop/brain-coloring/output/mi
ce-output'
```
Also strangely the input in the config file does not seem to need the absolute path for it to work.  Line 2 of my config file in unchanged and reads `INPUT_FILE = 'input/mouse_template.csv' # input template should match ATLAS below`

This did fix my problem, the images have been generated as intended I just thought you might want to be made aware of these small oddities.
