### ISSUE TITLE
Postive to negative color gradient and changing the color gradient legend labels

### ISSUE THREAD

**Issue by AngCamp** [razvanmarinescu/brain-coloring#20]
I am using your repository to display feature importance of different brain regions.  I want to convey postive and negative values on the same color gradient I want to make sure this is the correct way to do so.

So I will use the following change to the config.py file
```
# NOTE: you can add more than 4 colours (as many as you want), in which case you should increase the range of the input biomarkers.
COLORS_RGB = [(0,0,1), (0,0,0.5),(1,1,1),(0.5,0,0),(1,0,0)] # Blue ->White-> Red
```

My starting scale is from -4 to 4 so I would convert it to be between 0-6 (so a feature importance of 0 in my orginal data would become 3 (corresponding to white).

Lastly How can I get the color gradient bar legend to display the values as they relate to my orginal data?  So it would be marked as ranging from -4 to positive 4 rather than 0-5?

**Comment by razvanmarinescu** [comment]
Not sure I get the first question. 

For the second one, to show -4,4, you do as follows. You can add either 9 colors (-4 -3 -2 ... 2 3 4) or 5 colors (-4 -2 0 2 4), in the list. Then generate the images and compile the tex file (I think report.tex) with LaTeX. Then you can change the labels on the colorbar manually to whatever you need.

**Comment by AngCamp** [comment]
I think you've answered my question.  Where in the .tex file can I manually change the colors label? I'm not sure which line will let me do that.

Here is the .txt file of the mouse output from the tutorial:
```
\documentclass[11pt,a4paper]{report}
\usepackage{float}
\usepackage{tikz}
\usetikzlibrary{plotmarks}
\usepackage{amsmath,graphicx}
\usepackage{epstopdf}
\usepackage[font=normal,labelfont=bf]{caption}
\usepackage{subcaption}
\usepackage{color}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{scalefnt}

% margin size
\usepackage[margin=1in]{geometry}
%\documentclass[border=2pt,tikz]{standalone}
\usetikzlibrary{positioning}

\newcommand{\scl}{0.06}

\begin{document}\tikzset{block/.style={node distance=-1pt, line width=1pt}}
\begin{tikzpicture}
\centering

    \node[block,above=of 0] {Image 0};
    \end{tikzpicture}\tikzset{block/.style={node distance=-1pt, line width=1pt}}
\begin{tikzpicture}
\centering

    \node[block,above=of 0] {Image 1};
    \end{tikzpicture}\begin{tikzpicture}[scale=0.9,auto,swap]
    \definecolor{color_0}{rgb}{1, 1, 1}
    \definecolor{color_1}{rgb}{1, 1, 0}
    \definecolor{color_2}{rgb}{1, 0.4, 0}
    \definecolor{color_3}{rgb}{1, 0, 0}
    \shade[bottom color=color_0,top color=color_1] (0,0) rectangle (0.5,2.01);
    
    \shade[bottom color=color_1,top color=color_2] (0,2) rectangle (0.5,4.01);
    
    \shade[bottom color=color_2,top color=color_3] (0,4) rectangle (0.5,6.01);
     
    \draw (0,0) -- (0.5,0);\node[inner sep=0] (corr_text) at (1.6,0.0) {normal};
       
    \draw (0,2) -- (0.5,2);\node[inner sep=0] (corr_text) at (1.6,2.0) {1-sigma};
       
    \draw (0,4) -- (0.5,4);\node[inner sep=0] (corr_text) at (1.6,4.0) {2-sigma};
       
    \draw (0,6) -- (0.5,6);\node[inner sep=0] (corr_text) at (1.6,6.0) {3-sigma};
      

  \end{tikzpicture}
  \end{document}
```

**Comment by AngCamp** [comment]
I will try your solution and post the .txt file in a few minutes.

**Comment by AngCamp** [comment]
> Not sure I get the first question.
> 
> For the second one, to show -4,4, you do as follows. You can add either 9 colors (-4 -3 -2 ... 2 3 4) or 5 colors (-4 -2 0 2 4), in the list. Then generate the images and compile the tex file (I think report.tex) with LaTeX. Then you can change the labels on the colorbar manually to whatever you need.

So my understanding is I need to rescale my input for brainpainter because if I just put in my values with the negatives it wont accept that as input.  So I need to shift them into positive scale.  I wanted to make sure it would work for me to have a color gradient that starts at blue goes to white then goes to red.  I think based on your answer I am correct.

**Comment by razvanmarinescu** [comment]
Oh yes, that's correct. You have to scale your values to the positives, 0-MAX, to be more precise. Then BrainPainter will generate a colorbar 0-MAX. And you just manually change the labels at the end to -4,4.

**Comment by AngCamp** [comment]
Great, so the only thing I am confused abut is how to manually change the label? It is not obvious where in the report.txt this can be done.

**Comment by AngCamp** [comment]
Is it these lines?  Around line 38-44 in report.txt?
```
    \draw (0,0) -- (0.5,0);\node[inner sep=0] (corr_text) at (1.6,0.0) {normal};
       
    \draw (0,2) -- (0.5,2);\node[inner sep=0] (corr_text) at (1.6,2.0) {1-sigma};
       
    \draw (0,4) -- (0.5,4);\node[inner sep=0] (corr_text) at (1.6,4.0) {2-sigma};
       
    \draw (0,6) -- (0.5,6);\node[inner sep=0] (corr_text) at (1.6,6.0) {3-sigma};
      
```

**Comment by razvanmarinescu** [comment]
Yes. You need to edit and compile that code with a LaTeX editor & compiler. Everything from \begin{document} to \end{document}
