### ISSUE TITLE
Website internal error

### ISSUE THREAD

**Issue by araikes** [razvanmarinescu/brain-coloring#24]
Hi @razvanmarinescu,

I'm trying to run BrainPainter off the website and keep getting an 500 internal server error. Can you confirm that it is up and running?

Thanks

**Comment by razvanmarinescu** [comment]
Thanks. Myself or @vmallela0 will look into it shortly

**Comment by razvanmarinescu** [comment]
Meanwhile, you can try to run it locally on your computer through docker

**Comment by vmallela0** [comment]
Hi @araikes , sorry about that error! It should be working fine now.

**Comment by araikes** [comment]
Thanks @vmallela0. Looks like it's working.

@razvanmarinescu I don't have access to Docker unfortunately. I tried doing it via Singularity but I got a read/write permissions issue and didn't want to spend much time debugging it.
