### ISSUE TITLE
Question about the Destrieux atlas template

### ISSUE THREAD

**Issue by kacey-yang** [razvanmarinescu/brain-coloring#8]
I have another question about this tool.

I just noticed that the order of ROIs name in the Destrieux atlas template csv file is slightly different from the order in the original paper where the Destrieux atlas was proposed.
"Automatic parcellation of human cortical gyri and sulci using standard anatomical nomenclature"

I have an array of 148 ROIs values which is consistent with the order in the orginal paper, but the template has a different order of ROI.

Can I modify the order of ROIs name in the template csv file and fill in the corresponding values for each ROI? 
This means that the tool will match the values with the brain regions according to the ROIs name.

Or, the BrainPainter tool only takes the values by that order specified in the template csv file?

Thanks!

**Comment by kacey-yang** [comment]
Also, I noticed that the atlas template got updated by adding 'left/right' in front of the ROIs name.

Does it mean that the old version of template (as the one listed in browser tool webpage, without 'left/right') in no longer compatible with the BrainPainter?

**Comment by razvanmarinescu** [comment]
Regarding the first question, I think the order shouldn't matter, although I haven't tested for this. I just looked at the code, and it should work. If it doesn't, do write back to us.

Regarding the second question, Vedu will clarify, as he worked on that.

**Comment by kacey-yang** [comment]
Is it possible to make the ROI order in the Destrieux template consistent with the original paper?
Since that order is more widely used and accepted.

I've manually adjusted the ROI order in the old version of Destrieux template csv file to make it consistent with the order in the paper, but it should be much more convenient for users if the order is consistent in the first place. If not, we will still need to modify the ROI order in the new template with left/right.

**Comment by kacey-yang** [comment]
Can I ask about when we could expect the website to be updated? 
Then I will plan ahead for my own plotting work.

**Comment by vmallela0** [comment]
We can change the Destrieux template, but I just checked and the order of the csv data does not matter.

**Comment by vmallela0** [comment]
We're working through a few issues right now but they should be resolved ASAP. Sorry for the delay. (We'll shoot for either tomorrow or Monday).

**Comment by kacey-yang** [comment]
Thank you for your reply!

It is better users can have the .csv template with the same order as in Destrieux atlas paper.

The reason is that usually when we are working with Destrieux atlas, the neuroimaging dataset has the same ROI order as in the Destrieux atlas paper.
This means that when we need to plot the ROI measurements on the brain surface, it is an array of 148 values with the same order as in the Destrieux atlas paper. 

If the .csv template has the same order, when we fill in the template, we can simply copy and paste the whole array directly at once.
However, if the .csv template has a different order, then we either have to modify the template columns manually on our own, or we have to modify the order in the array every time we need the plot. 
If we don't do the modifications, then we have to manually fill all the 148 values in the current .csv template with a different ROI order.

Hope that you could understand why it would be much convenient for users if the .csv template has the same ROI order as in the Destrieux atlas paper.

Thank you!

**Comment by vmallela0** [comment]
That makes sense, I can make that change ASAP. Thanks for your suggestion :)
