### ISSUE TITLE
Blender error after install 

### ISSUE THREAD

**Issue by kmbond** [razvanmarinescu/brain-coloring#9]
after i call `make`, i get this error (this is on MacOS Big Sur, version 11.2.3): 

`configFile=config.py /Applications/Blender/blender.app/Contents/MacOS/blender --background --python blendCreateSnapshot.py `
`/bin/sh: 1: /Applications/Blender/blender.app/Contents/MacOS/blender: not found  `
`Makefile:2: recipe for target 'all' failed  `
`make: *** [all] Error 127`

Is there possibly a dependency/step missing in the instructions for installation using Docker?  

Thanks in advance for your help!

**Comment by vmallela0** [comment]
Hi, this means that the Blender application is not at that path. Are you sure that you installed Blender 2.79b (https://download.blender.org/release/Blender2.79/). 
If that is not the issue, then could you please locate where the blender application is on your machine. Once you find the location, you can replace the path ('/Applications/Blender/blender.app/Contents/MacOS/blender') with the path on your computer. 

I hope this helps. Feel free to ping us again if you need any more help. 

Best, 
Vedu

**Comment by nosmokingsurfer** [comment]
@kmbond I've ran into the same problem. You need to edit the MakeFile in brain-painter home directory and provide the path to the blender executable.

I've spent some time figuring out how to configure blender and brain-painter. There will some other steps not so obvious, at least for me.

Here I've tried to record the step-by-step video instruction for my colleagues, hope it will help you too:
https://youtu.be/rzGb40PUVX8

**Comment by vmallela0** [comment]
Wow! Thanks for making a video tutorial @nosmokingsurfer. It looks awesome :)

**Comment by razvanmarinescu** [comment]
@nosmokingsurfer that's fantastic! We will link your video to the main install instructions. 

Also, I was just thinking. Would it work if we create a zip archive with blender 2.79, for Ubuntu x64, with the **right** python packages? And offer this blender for download instead? And perhaps do the same for MacOS and Windows?

**Comment by nosmokingsurfer** [comment]
@razvanmarinescu I think it will, at least for Ubuntu. You can try mine from the video it is already with right packages installed:
https://drive.google.com/file/d/1HBENRhMB3UPLQOBLmn6mDZEgU33RD-og/view?usp=sharing

**Comment by kmbond** [comment]
> @kmbond I've ran into the same problem. You need to edit the MakeFile in brain-painter home directory and provide the path to the blender executable.
> 
> I've spent some time figuring out how to configure blender and brain-painter. There will some other steps not so obvious, at least for me.
> 
> Here I've tried to record the step-by-step video instruction for my colleagues, hope it will help you too:
> https://youtu.be/rzGb40PUVX8

Thank you so much @nosmokingsurfer!
